"""Compiler-native source-first v3 primitives."""

from .ast_ir import (
    IR_VERSION,
    OPAQUE_MARKER_PREFIX,
    OPAQUE_MARKER_SUFFIX,
    AstNode,
    FootnoteNode,
    FootnoteRenderContext,
    FootnoteRenderer,
    FootnoteRendererRequired,
    InvalidAtomSelection,
    MathMacroDefinition,
    SourceAtom,
    SourceDocumentIR,
    SourceIrError,
    SourceNode,
    SourceSpan,
    atoms_to_markdown,
    build_source_ir,
    parse_source_ir,
    reconstruct_markdown,
)

__all__ = [
    "IR_VERSION",
    "OPAQUE_MARKER_PREFIX",
    "OPAQUE_MARKER_SUFFIX",
    "AstNode",
    "FootnoteNode",
    "FootnoteRenderContext",
    "FootnoteRenderer",
    "FootnoteRendererRequired",
    "InvalidAtomSelection",
    "MathMacroDefinition",
    "SourceAtom",
    "SourceDocumentIR",
    "SourceIrError",
    "SourceNode",
    "SourceSpan",
    "atoms_to_markdown",
    "build_source_ir",
    "parse_source_ir",
    "reconstruct_markdown",
]
